name: CI

on:  
  push:
    branches: main

jobs:
  build:   
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # instalar dependencias npm/yarn
      - name: Install dependencies
        run: yarn
      
      # executar build   
      - name: Run build
        run: yarn build

      # remover pasta remota
      - name: Remove old directory on AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
           sudo rm -rf ~/messageChatApi

      # copiar codigo para dentro da digital ocean
      - name: Copy dist to AWS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!node_modules"
          target: "~/messageChatApi"
          timeout: 120s

      # run production scripts
      - name: Install dependencies on AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/messageChatApi
            yarn
            npx prisma generate
            yarn prisma migrate deploy
            pm2 restart messageChatApi
