name: CI

on:  
  push:
    branches: main

jobs:
  build:   
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # instalar dependências npm/yarn
      - name: Install dependencies
        run: yarn
      
      # executar build   
      - name: Run build
        run: yarn build

      # limpar a pasta remota antes de copiar
      - name: Clean remote folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # garante que o usuário tem permissão
            mkdir -p ~/messageChatApi
            rm -rf ~/messageChatApi/*

      # copiar código para o servidor
      - name: Copy dist to AWS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!node_modules"
          target: "~/messageChatApi"
          timeout: 120s
    
      # rodar scripts de produção
      - name: Install dependencies on AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/messageChatApi
            yarn
            npx prisma generate
            pm2 restart messageChatApi
